services:
  - type: web
    name: rate-limiter
    runtime: docker
    repo: https://github.com/vikingmanas/Rate_Limit
    branch: main
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: JAVA_OPTS
        value: -Xmx256m
